### ISSUE TITLE
Chat Reports

### ISSUE THREAD

**Issue by m1lklinG** [coffiarts/FoundryVTT-lock-the-sheets#3]
When activating / deactivating the LOCK-effect there are chat messages for every token the effect applies to / has been removed from.
I would prefer an option to deactivate these reports since the popup message and/or the UI button highlighting totally work for me.

**Comment by coffiarts** [comment]
That's weird, because neither did I implement any chat messages (only the mentioned UI messages), nor would I do such a thing per affected actor (which would be a stupid feature indeed ;-)).
So I can only assume for a start that there's another mod interfering?
Happen to have a screenshot of such a chat entry?

**Comment by m1lklinG** [comment]
There you go :) 

<img width="216" alt="image" src="https://github.com/user-attachments/assets/956d069b-076e-4644-9985-a9dbbf641c70">

**Comment by coffiarts** [comment]
Right, that's definitely not from my mod.
Have you checked the browser console yet? Many mods also log  to console whatever they're posting to the chat or UI (which is a good practice anyway IMO).
There you might find some hints.

**Comment by m1lklinG** [comment]
Found it.
It is an option within the tde5 basic settings to report to GM if any effect on a character ends.

#Solved

Thank you :)
